name: Deploy master

on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Generate deployment package
      run: zip -r Whatsup_AWS.zip . -x '*.git*'
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v11
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: TEST
        environment_name: Test-env
        version_label: "test-app-${{ steps.format-time.outputs.replaced }}"
        region: ap-northeast-2
        deployment_package: Whatsup_AWS.zip
